# Generated by Django 5.2.4 on 2025-07-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gallery_interior_interiorstyle_interiorimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiorstyle',
            name='budget',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interiorstyle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interiorstyle',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interiorstyle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='interior/styles/'),
        ),
        migrations.AddField(
            model_name='interiorstyle',
            name='timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
