# Generated by Django 5.2.4 on 2025-07-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_interiorstyle_budget_interiorstyle_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interiorimage',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='interiorstyle',
            name='image',
        ),
        migrations.CreateModel(
            name='InteriorStyleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='interior/styles/images/')),
                ('interior_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.interiorstyle')),
            ],
        ),
        migrations.DeleteModel(
            name='Interior',
        ),
        migrations.DeleteModel(
            name='InteriorImage',
        ),
    ]
